# Generated by Django 4.2.9 on 2024-01-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50)),
                ('steps', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
            ],
        ),
    ]
